# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181010_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Other', 'Other')], default=1, max_length=6),
        ),
    ]
