# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_uploadedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploadedBy',
            field=models.CharField(blank=True, default='admin', max_length=254),
        ),
    ]
